# -*- coding: utf-8 -*-
"""TFLite_Colab_June2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GLoKSrWwOrH53wqRNwargNIYJB8UECb5

# Work-around for TFlite Model Maker in Google Colab (June 2023)

This is a forced work around for the recent update of google colab to Python 3.10, which fails to support tflite.

As such, the strategy is to run tflite in a python 3.9 environment using a virtual machine with anaconda platform.
"""

# Commented out IPython magic to ensure Python compatibility.
# %env PYTHONPATH = # /env/python

!wget https://repo.anaconda.com/miniconda/Miniconda3-py39_23.3.1-0-Linux-x86_64.sh
!chmod +x Miniconda3-py39_23.3.1-0-Linux-x86_64.sh
!./Miniconda3-py39_23.3.1-0-Linux-x86_64.sh -b -f -p /usr/local
!conda update conda

"""#Import System Package (Which Include Conda)"""

import sys
sys.path.append('/usr/local/lib/python3.9/site-packages')

"""# Create Python 3.9 Environment"""

!conda create -n myenv python=3.9

"""# Note !!! Use of Conda

To activate this environment, use

**$ conda activate myenv**


To deactivate an active environment, use

**$ conda deactivate**

### Install the required packages
Start by installing the required packages, including the Model Maker package from the [GitHub repo](https://github.com/tensorflow/examples/tree/master/tensorflow_examples/lite/model_maker) and the pycocotools library you'll use for evaluation.
"""

# Commented out IPython magic to ensure Python compatibility.
# # The first THREE lines of commands are required to activate conda environment at python 3.9
# %%shell
# eval "$(conda shell.bash hook)"
# conda activate myenv
# 
# #Packages required by tflite
# pip install ipykernel #do not touch
# pip install roboflow
# pip install numpy==1.23.4
# pip install -q tflite-model-maker
# pip install -q pycocotools
# pip install "opencv-python-headless < 4.3"
# pip uninstall -y tensorflow && pip install -q tensorflow==2.8.0

"""#Run your code

You need to clean up all the commands associated to package install and put them on top like what i did.

In your code, only start with from packagename .... or import packagename ...
"""

!pip install --upgrade roboflow

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# eval "$(conda shell.bash hook)"
# conda activate myenv
# python /content/capstone.py #You will have to load your notebook as a .py file. Change the filename accordingly to yours